language: node_js
node_js:
  - 10
addons:
  chrome: stable
script:
  - yarn build
  - yarn test:build
  - yarn test
deploy:
  provider: npm
  email: rpgmorpheus@gmail.com
  api_key:
    secure: WsfSLDj8DP26LKRxkbQpGLayHh7gKgHVbGm++A5oFSNsRkGVLE2yLsd8wLkp8Ir7SXdiskA9aIdLsnuVtjeGjZner2alMiMc5fJa5KPR2L4jxRPZK/5urK4bjSKPqCkcoVQ1W9PJO+dc3mq76KTGuaiPtL2V+iY3IsODVPaJ4guuIFa7zJOCe3kOZ+yxWQEIrpZiQhY0Q9jNixYOwDouXgS18JQgVjlpJK59loLpQjU9DTNQXX5W3LCPT0K6ZrPa71o1cZBvZ2IxpvbALOciu1I5qaWuP2oWwfn4X3Kjd0DtZdIuLfMsvyuJU0FH3Gn3NlrIts6eS2M6DNbgr5w8HITtNKMt1NNrJYfEldUDVsQRGq2Xzuiz7ny/jaTkL8CEQY2RBoqXEvY+LQaVFFkAKAb9q6L7ArwcZwZScm5kskt4jUFrLeFtCLgQM7oCHbXUWUmTznrvXKZPobSKT8VRLzGHnSP8l2uEv9zYLkDsvJn24SrwIY0Fgu0b7XN65x4GfuZiheEzCbe+QTx6EQ1wqSSMr9oVf32444usJgEKDVd0n4UqxsJVkzMg6pZspAw1nTw2vTPrxg7pCIgK4vDJ3KjwTcvuRaprKXC7kJRwxuToISzGFXtlrPzQvSaQ/+7Ik4Nkx+ShHwZ0XNAGyiBWvOXYNOR94V4c4UicLuE1Cfc=
  on:
    tags: true
    repo: ZeeCoder/react-resize-observer
  skip_cleanup: true
